# Generated by Django 5.2.14 on 2026-06-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0003_rename_pudricion_to_sarna'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='webhook_url',
            field=models.URLField(blank=True),
        ),
    ]
