# Generated by Django 5.2.14 on 2026-07-17 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classifications",
            "0004_classification_deleted_at_classification_webhook_url",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lot_name",
                    models.CharField(max_length=100, verbose_name="Nombre del lote"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Descripción"
                    ),
                ),
                (
                    "lot_status",
                    models.CharField(
                        choices=[
                            ("in_progress", "En proceso"),
                            ("completed", "Completado"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="Estado del lote",
                    ),
                ),
                ("total_images", models.PositiveIntegerField(default=0)),
                ("healthy_count", models.PositiveIntegerField(default=0)),
                ("anthracnose_count", models.PositiveIntegerField(default=0)),
                ("scab_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote",
                "verbose_name_plural": "Lotes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="classification",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classifications",
                to="classifications.lot",
            ),
        ),
        migrations.AddConstraint(
            model_name="lot",
            constraint=models.UniqueConstraint(
                fields=("user", "lot_name"), name="unique_lot_per_user"
            ),
        ),
    ]
