# Generated by Django 5.2.14 on 2026-07-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifications", "0005_lot_classification_lot_lot_unique_lot_per_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="classification",
            name="east_coordinate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Coordenada Este (m)",
            ),
        ),
        migrations.AddField(
            model_name="classification",
            name="north_coordinate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Coordenada Norte (m)",
            ),
        ),
        migrations.AddField(
            model_name="classification",
            name="tree_code",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Código del árbol"
            ),
        ),
    ]
